---

- name: hubot vpc
  ec2_vpc:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_access_key }}"
    region: "{{ aws_region }}"
    state: present
    cidr_block: "{{ cidr }}"
    resource_tags:
      Name: hubot
    subnets:
      - cidr: "{{ public_subnet }}"
        az: "{{ public_subnet_az }}"
        resource_tags: { "Subnet":"Public" }
      - cidr: "{{ private_subnet }}"
        az: "{{ private_subnet_az }}"
        resource_tags: { "Subnet":"Private" }
    internet_gateway: True
    route_tables:
      - subnets:
          - "{{ public_subnet }}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
        resource_tags:
          Name: hubot
      - subnets:
          - "{{ private_subnet }}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
        resource_tags:
          Name: hubot
  register: aws_vpc
