---

- name: set random private subnet
  set_fact:
    prv_subnet="{{ aws_vpc_private_subnets | random }}"

- name: set random public subnet
  set_fact:
    pub_subnet="{{ aws_vpc_public_subnets | random }}"

- name: provision hubot node
  local_action:
    module: ec2
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_access_key }}"
    region: "{{ aws_region }}"
    key_name: hubot
    group: hubot
    instance_type: "{{ instance_type }}"
    image: "{{ aws_ami[aws_region] }}"
    wait: yes
    wait_timeout: 600
    count: 1
    instance_profile_name: hubot
    instance_tags:
      Name: hubot
    ebs_optimized: no
    monitoring: no
    vpc_subnet_id: "{{ pub_subnet.id }}"
    assign_public_ip: yes
  register: ec2

- name: wait for ssh to be available
  wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2.instances }}"